### ISSUE TITLE
Editor stops working on right-click on component from this Gem

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/o3de-ros2-gem#217]
**Bug description**
Like in the title, the left click on component delivered by this Gem cause Editor to crash.

**To Reproduce**
1. Open sample project (e.g.  Ros2WarehouseDemo)
2. Open level
3. Select robot base link
4. Right click on component (e.g. ROS2 Frame)
5. Editor stops

**Expected behavior**
normal behavior on right click.

**Screenshots / videos**
If applicable, add screenshots/videos to help explain your problem.

**Test environment**
 - OS: Ubuntu 22.04
 - ROS: Humble

**Additional context**
The danger zone is marked with red frame :
![image](https://user-images.githubusercontent.com/3209244/191530878-dd562f44-2aaa-473e-ba8c-afdc1237fd0b.png)

**Comment by adamdbrw** [comment]
More details found by @michalpelka:
The crash is in 
`Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp`
```
 AzToolsFramework::Components::EditorComponentBase* editorComponent = static_cast<AzToolsFramework::Components::EditorComponentBase*>(component);

AZ_Printf("FOOBAR", "editorComponent %ld \n", editorComponent->GetId());
if (editorComponent)
{
   editorComponent->AddContextMenuActions(&menu);
}
```

Seems like something is wrong with handling Components without explicitly defined EditorComponents.

**Comment by michalpelka** [comment]
The whole situation looks like we have a problem in polymorphism that is visible in runtime.
The code crashes in ` EntityPropertyEditor::RequestPropertyContextMenu`. 
The logic there is like that:
- Our component (e.g. `ROS2FrameComponent`) is taken here. 
- It is static-casted to various parent types.
- Casting to `AZ::Component` works fine
- Casting to `AzToolsFramework::Components::EditorComponent` is performed. It gives some pointer.
- This pointer however is not valid since `ROS2FrameComponent` does not inherit from `AzToolsFramework::Components::EditorComponent`
- The whole program crashes down the road `editor component->AddContextMenuActions(&menu);`  since the program tries to do something on an invalid piece of memory given udefined behavior (crash luckily).
One more note:
- the whole thing works fine when we switch to EditorComponent like [here ](https://github.com/RobotecAI/o3de-ros2-gem/pull/218/commits/7cf28af74b6f7a57f4e1ef43e5410fdda33084b2#)

**Comment by nick-l-o3de** [comment]
theres at least 2 bugs here.

First, this should check for a failed cast and not crash.  Perhaps with an error message.
But second, it should never get into the situation where an EditorComponent-based class is not in the base cast.  

If ROS2FrameComponent does not inherit from EditorComponent, what should happen is attempting to put it on the entity itself should instead automatically create a GenericWrapperComponent<ROS2FrameComponent> and put that generic wrapper, which _is_ an EditorComponent, on the entity instead.  So in edit mode, all components on the entity should always be EditorComponent-derived.

How is the ROS2FrameComponent being added to the entity?  Adding it via the GUI should be automatically noticing that its not derived from EditorComponent, automatically create a GenericWrapperComponent<ROS2FrameComponent>, and add that instead.   If its being added programatically or via prefab it probably needs to update that code so that it also makes the generic wrapper.

**Comment by michalpelka** [comment]
I can see that URDF importer creates Components in the wrong way. When components are created in Editor, they are handled correctly by `Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp` 
I will fix that in URDF importer.

**Comment by adamdbrw** [comment]
Perhaps it is best to add a utility function which encapsulates all that

**Comment by michalpelka** [comment]
Yes, the change will be a little large - it seems that we cannot pass parameters that we used to pass with a constructor.
A good example here is 
````
        ControlConfiguration controlConfiguration;
        controlConfiguration.m_robotConfiguration.m_body = rootEntityId;
        controlConfiguration.m_broadcastBusMode = false;
        controlConfiguration.m_topic = "cmd_vel";
        AZ::Entity* rootEntity = AzToolsFramework::GetEntityById(rootEntityId);
        rootEntity->CreateComponent<ROS2RobotControlComponent>(controlConfiguration)
````
 Should we expose those all parameters with setters?
 The second question considers components that are already EditorComponents like:
````
entity->CreateComponent<PhysX::EditorRigidBodyComponent>(rigidBodyConfiguration, physxSpecificConfiguration);
````
Those often expose crucial features with their constructors.

**Comment by adamdbrw** [comment]
Wouldn't it be
CreateComponent (as now)
Do some additional things
?
