### ISSUE TITLE
Standards and styles / Miscellaneous / Part I

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-ros2-gem#310]
Apply the following guidelines to the code base:
- [x] [Use AZ or AZStd](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#use-az-or-azstd)
- [x] [Use of auto](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#use-of-auto)
- [x] [Use of nullptr](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#use-of-nullptr)
- [x] [C++ Exceptions](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#c-exceptions)

**Comment by forhalle** [comment]
Thanks for your work on this @michalpelka! I'm re-opening, however, because we would like to include at least one SIG reviewer who was involved in this project (i.e. Derric, Steve, Alex, Tom, etc.) on each task to review the standards. 

Please feel free to continue work on the tasks on this board, but please do not set them to "Done"... We will let the SIG reviewers do that. Instead, feel free to leave comments in the tasks as to the work you have performed.
