### ISSUE TITLE
Nav Stack: Review code for O3DE Standards

### ISSUE THREAD

**Issue by forhalle** [RobotecAI/o3de-ros2-gem#360]
Ensure O3DE standards for documentation and license headers.

**Comment by michalpelka** [comment]
Here is the PR with the navigation state (RO2 packages) migrated : 
https://github.com/o3de/ROSConDemo/pull/202 
This PR is created from main branch of this repository: https://github.com/RobotecAI/o3de_kraken_nav

**Comment by michalpelka** [comment]
PR with progress on documenting navigation code :
https://github.com/o3de/ROSConDemo/pull/211

**Comment by adamdbrw** [comment]
@forhalle 
The navigation stack is **not O3DE code, it is ROS 2 code**.

It does not use anything from O3DE, link to O3DE and so on. I do not believe many of these are applicable. ROS2 has its own standards, please see https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#id2.

I believe that having ROS code in O3DE standard **could be confusing for ROS developers** (who are used to ROS standards). There are some items in this task which can be applied (are agnostic to ROS standards), but some of them are in opposition (for example, naming of variables, snake_case vs camelCase). Moreover, things like the use of AZStd libraries do not apply as these libraries are not available for this ROS code at all.

I suggest to have documentation and license headers as per O3DE standards, but otherwise apply ROS 2 standards to ROS code in the package. What do you think?

**Comment by spham-amzn** [comment]
> @forhalle The navigation stack is **not O3DE code, it is ROS 2 code**.
> 
> It does not use anything from O3DE, link to O3DE and so on. I do not believe many of these are applicable. ROS2 has its own standards, please see https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#id2.
> 
> I believe that having ROS code in O3DE standard **could be confusing for ROS developers** (who are used to ROS standards). There are some items in this task which can be applied (are agnostic to ROS standards), but some of them are in opposition (for example, naming of variables, snake_case vs camelCase). Moreover, things like the use of AZStd libraries do not apply as these libraries are not available for this ROS code at all.
> 
> I suggest to have documentation and license headers as per O3DE standards, but otherwise apply ROS 2 standards to ROS code in the package. What do you think?

The Nav Stack is Python code, and the oinly requirements for python code is PEP-8 and the copyright attribution, I do not think the list above applies

**Comment by michalpelka** [comment]
Revied code to ROS2 standards and merged.
